name = "dgr-live-world-status"
pages_build_output_dir = "."
compatibility_date = "2026-08-08"

[[d1_databases]]
binding = "DB"
database_name = "dgr-live-world-history"
database_id = "913f1956-e135-4a96-823c-3c315f37ead3"
